name: magrail_app
description: Tinygrail mobile client
publish_to: none
version: 1.1.2+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  cookie_jar:
  crypto:
  dio:
  dio_cookie_manager:
  flutter_bloc:
  flutter_secure_storage:
  flutter_svg:
  gal:
  go_router:
  extended_image:
  image:
  image_picker:
  infinite_scroll_pagination:
  intl:
  lucide_flutter:
  material_symbols_icons:
  mime:
  package_info_plus:
  path_provider:
  shared_preferences:
  signalr_netcore:
  skeletonizer:
  url_launcher:
  webview_flutter:
  liquid_glass_widgets: ^0.19.1

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon_foreground.png
    - assets/icons/github.svg
    - assets/icons/torii.svg
    - assets/images/donate/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/noto_sans_sc_wght.ttf
